# Generated by Django 3.0.3 on 2020-09-07 11:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('webmap', '0001_country_mapspot'),
    ]

    operations = [
        migrations.DeleteModel(
            name='MapSpot',
        ),
        migrations.RenameField(
            model_name='country',
            old_name='lat_long',
            new_name='location',
        ),
    ]
